import { useEffect, useState } from 'react'
import { ArrowDown, ArrowRight, ExternalLink, Menu, Play, X } from 'lucide-react'
import { credits, socials } from './content.js'

const nav = [['Work', 'work'], ['Credits', 'credits'], ['Modeling', 'modeling'], ['About', 'about'], ['Contact', 'contact']]
const photo = n => `${import.meta.env.BASE_URL}IMG_${n}.jpeg`

function SectionLabel({ number, children }) { return <p className="eyebrow"><span>{number}</span>{children}</p> }
function Photo({ n, alt, className='' }) { return <div className={`photo ${className}`}><img src={photo(n)} alt={alt} loading="lazy" /></div> }

function Header() {
  const [open, setOpen] = useState(false)
  useEffect(() => { const close=()=>setOpen(false); window.addEventListener('hashchange',close); return()=>window.removeEventListener('hashchange',close) }, [])
  return <header><a className="monogram" href="#top">SV</a><button className="menu-button" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{nav.map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)}>{label}</a>)}</nav><a className="header-contact" href="#contact">Inquiries <ArrowRight size={15}/></a></header>
}

function App(){return <>
<a className="skip" href="#main">Skip to content</a><Header/><main id="main">
<section className="hero" id="top"><img className="hero-photo" src={photo(9449)} alt="Sammy Velez"/><div className="hero-shade"/><div className="hero-content"><p className="kicker">The official website of</p><h1>Sammy<br/><em>Velez</em></h1><p className="roles">Actor <i/> Model <i/> Comedian <i/> Content Creator</p><div className="hero-actions"><a className="button light" href="#reels"><Play size={15} fill="currentColor"/> View Reel</a><a className="button ghost" href="#credits">View Credits</a><a className="text-link" href="#contact">Contact <ArrowRight size={15}/></a></div></div><a className="scroll" href="#intro"><ArrowDown size={18}/><span>Explore</span></a></section>
<section className="intro section" id="intro"><SectionLabel number="01">Introduction</SectionLabel><div className="intro-grid"><h2>Actor. Model.<br/>Comedian. <em>Creator.</em></h2><div><p>Sammy Velez brings range, personality, and presence to screen, stage, digital media, and modeling.</p><p className="muted">Explore selected performances, credits, professional photography, comedy, and original content.</p></div></div><div className="preview-grid" id="work"><a href="#reels" className="preview"><Photo n={9443} alt="Sammy Velez acting portrait"/><span>01 / Moving image</span><h3>Acting & Reels <ArrowRight/></h3></a><a href="#modeling" className="preview"><Photo n={9442} alt="Sammy Velez modeling portrait"/><span>02 / Editorial</span><h3>Modeling <ArrowRight/></h3></a><a href="#comedy" className="preview"><Photo n={9440} alt="Sammy Velez commercial portrait"/><span>03 / Personality</span><h3>Comedy & Content <ArrowRight/></h3></a></div></section>
<section className="reels section" id="reels"><SectionLabel number="02">Acting / Reels</SectionLabel><div className="split-heading"><h2>On <em>screen.</em></h2><p>Selected screen work, performances, and digital appearances.</p></div><div className="acting-feature"><Photo n={9444} alt="Sammy Velez dramatic acting portrait"/><div><span>ACTOR / PERFORMER</span><h3>Character. Presence. Range.</h3><p>Film, digital productions, comedy performance, and on-camera work.</p></div></div><div className="media-list">{['Vid Chronicles — YouTube work','LA Connection Comedy — Performance material','No Fugaze Podcast with David Cooley — Appearance'].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div></section>
<section className="credits section" id="credits"><SectionLabel number="03">Selected Credits</SectionLabel><div className="split-heading"><h2>Professional<br/><em>work.</em></h2><div className="credit-actions"><a className="button outline" href="https://www.imdb.com/name/nm18195530/" target="_blank" rel="noreferrer">IMDb <ExternalLink size={15}/></a><a className="button outline" href="https://resumes.actorsaccess.com/sammyvelez" target="_blank" rel="noreferrer">Actors Access <ExternalLink size={15}/></a></div></div><div className="credit-table"><div className="credit-row heading"><span>Project</span><span>Format / Source</span></div>{credits.map(({title,type})=><div className="credit-row" key={title}><strong>{title}</strong><span>{type}</span></div>)}</div></section>
<section className="modeling section" id="modeling"><div className="model-copy"><SectionLabel number="04">Modeling</SectionLabel><h2>Presence in<br/><em>every frame.</em></h2><p>Professional, commercial, lifestyle, and fitness imagery.</p><a className="button light" href="https://sammyvelez.modelingfolio.com" target="_blank" rel="noreferrer">View portfolio <ExternalLink size={15}/></a></div><div className="model-grid"><Photo n={9441} alt="Sammy Velez professional portrait"/><Photo n={9445} alt="Sammy Velez lifestyle portrait"/><Photo n={9446} alt="Sammy Velez full body professional portrait"/></div></section>
<section className="comedy section" id="comedy"><SectionLabel number="05">Comedy / Content</SectionLabel><div className="split-heading"><h2>Stories with<br/><em>an edge.</em></h2><Photo n={9447} alt="Sammy Velez portrait" className="comedy-photo"/></div><div className="content-cards">{[['Performance','LA Connection Comedy'],['Digital','Vid Chronicles'],['Conversation','No Fugaze Podcast appearance']].map(([type,title],i)=><article key={title}><span>0{i+1} — {type}</span><h3>{title}</h3></article>)}</div></section>
<section className="about section" id="about"><div><SectionLabel number="06">About</SectionLabel><h2>Meet<br/><em>Sammy.</em></h2><Photo n={9448} alt="Sammy Velez" className="about-photo"/></div><div className="about-copy"><p className="lead">Actor, model, comedian, content creator, and entertainment professional.</p><p>Sammy's work spans film, digital productions, live improv, modeling, voice performance, and original content.</p><div className="pending"><span>Professional profile</span><b>6'1” · Black Hair · Brown Eyes</b></div></div></section>
<section className="contact section" id="contact"><SectionLabel number="07">Professional Inquiries</SectionLabel><h2>Let’s create<br/><em>something memorable.</em></h2><div className="contact-grid"><p>For casting, production, modeling and brand opportunities, comedy appearances, or professional collaborations.</p><div className="inquiry-types">{['Casting inquiries','Production inquiries','Modeling + brand','Comedy appearances','Collaborations'].map(x=><span key={x}>{x}<ArrowRight size={16}/></span>)}</div></div></section>
</main><footer><a className="footer-name" href="#top">Sammy <em>Velez</em></a><div className="socials">{socials.map(([label,url])=><a key={label} href={url} target="_blank" rel="noreferrer">{label}<ExternalLink size={11}/></a>)}</div><div className="footer-bottom"><span>© {new Date().getFullYear()} Sammy Velez</span><span>Official website</span><a href="#top">Back to top ↑</a></div></footer></>}
export default App
